### ISSUE TITLE
Distribute library

### ISSUE THREAD

**Issue by nmilcoff** [strazzere/anti-emulator#13]
Hi, thanks for all your hard work! I was wondering if you have any plans / if it's possible to distribute this library through Maven or any other dependency system. 

I would like to make your code available for Xamarin apps through a [Binding Library](https://docs.microsoft.com/en-us/xamarin/android/platform/binding-java-library/binding-an-aar) and having the package available like that would speed up the process :)

**Comment by strazzere** [comment]
No plans, you're welcome to make it into a jar and publish it, assuming you follow the licensing and retain all the credits.

Appreciate you opening an issue and asking though!
