### ISSUE TITLE
[Q] Manifest - MaxSdkVersion

### ISSUE THREAD

**Issue by MarMarIV** [strazzere/anti-emulator#19]
HI, i have a question. 

Is there any reason for this attribute in manifest?

https://github.com/strazzere/anti-emulator/blob/81973a6405f0960b745805049dc8cd57f627fd72/AntiEmulator/AndroidManifest.xml#L8

Thanks

**Comment by strazzere** [comment]
No - it likely was auto-filled by the tooling at the time. Nothing in this should explicitly break above 29 that I know of.

If you want to test and ensure this, then do a PR - we could close this issue? Otherwise I'll try to get to it this weekend or sometime.

**Comment by MarMarIV** [comment]
Tested on real device, running: https://github.com/strazzere/anti-emulator/pull/21

**Comment by strazzere** [comment]
Appreciate you taking the time for the question, filing an issue and making a pull request to close it.

It's always nice when open source goes this way :1st_place_medal: -- have a good one!
