### ISSUE TITLE
found debug .so in real device

### ISSUE THREAD

**Issue by orangetangerine** [strazzere/anti-emulator#4]
I am here again..
found "libc_malloc_debug_qemu.so" in /system/lib in some ROMs like CyanogenMod... 
I just simply remove this file in the "knowns file array" to let the detection work

**Comment by strazzere** [comment]
Interesting. Sounds like people are mis-compiling the ROMs as that is never need on a real device. I'll keep the issue around but not going to "fix" this as I still think it's out of scope for this project (again, people should know what they're attempting to actually detect)
