### ISSUE TITLE
FATAL EXCEPTION on System.loadLibrary("anti");

### ISSUE THREAD

**Issue by zigzag-way** [strazzere/anti-emulator#5]
The app crashes on 
System.loadLibrary("anti");
in FindEmulator.java

**Comment by strazzere** [comment]
Did you compile the jni code? Did it fail to build it?

This is a shared library which should get compiled.

**Comment by zigzag-way** [comment]
Oh... I did`nt understand that it`s a library.... so I just tried to use the source in my app )))

**Comment by zigzag-way** [comment]
Sorry, can you explain how can I build and use it? Where can I get the jar?

**Comment by strazzere** [comment]
These are example of how you could detect an emulator -- you can import the project into Android Studio / IntelliJ and use it from there. Or you can look at the source and take specific examples out.
